export const END_REGISTER_REQUEST = 'END_REGISTER_REQUEST';
export const END_REGISTER_SUCCESS = 'END_REGISTER_SUCCESS';
export const END_REGISTER_FAIL = 'END_REGISTER_FAIL';
export const END_REQUEST = 'END_REQUEST';
export const END_REQUEST_SUCESS = 'END_REQUEST_SUCESS';
export const END_REQUEST_FAIL = 'END_REQUEST_FAIL';