export const ENDERECO_REGISTER_REQUEST = 'ENDERECO_REGISTER_REQUEST';
export const ENDERECO_REGISTER_SUCCESS = 'ENDEREO_REGISTER_SUCCESS';
export const ENDERECO_REGISTER_FAIL = 'ENDERECO_REGISTER_FAIL';